package br.com.sixinf.judokas.entidades;

// Generated Jan 9, 2014 12:27:35 PM by Hibernate Tools 3.4.0.CR1

import java.io.Serializable;
import java.util.Date;
import java.util.Set;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import javax.persistence.GenerationType;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.SequenceGenerator;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

import br.com.sixinf.ferramentas.persistencia.Entidade;

/**
 * Usuario generated by hbm2java
 */
@Entity
@Table(name = "usuario", schema = "public")
public class Usuario implements Entidade, Serializable {

	private static final long serialVersionUID = 1L;
	public static final String SESSION_NOME_USUARIO = "usuario";
	public static final String SESSION_TIPO_USUARIO = "tipo_usuario";
	
	@Id
	@SequenceGenerator(name="seqUsuario", sequenceName="usuario_id_seq")
	@GeneratedValue(strategy=GenerationType.IDENTITY, generator="seqUsuario")
	@Column(name="id")
	private Long id;
	
	@Column(name = "usuario", length = 30)
	private String nomeUsuario;
	
	@Column(name = "senha", length = 30)
	private String senha;
	
	@Column(name = "primeiro_login")
	private Boolean primeiroLogin;
	
	@Column(name = "tipo_usuario", length = 10)
	private String tipoUsuario;
	
	@Column(name = "nome", length = 500)
	private String nome;
	
	@Column(name = "email", length = 80)
	private String email;
		
	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "data_registro", length = 29)
	private Date dataRegistro;
	
	@Column(name = "status_registro", length = 1)
	private Character statusRegistro;
	
	@OneToMany(fetch=FetchType.LAZY, mappedBy="usuario")
	private Set<Atleta> atletas;
	
	public Usuario() {
	}

	public Usuario(Long id) {
		this.id = id;
	}

	public Long getId() {
		return id;
	}

	public void setId(Long id) {
		this.id = id;
	}
	
	public String getNomeUsuario() {
		return nomeUsuario;
	}

	public void setNomeUsuario(String nomeUsuario) {
		this.nomeUsuario = nomeUsuario;
	}

	public String getSenha() {
		return this.senha;
	}

	public void setSenha(String senha) {
		this.senha = senha;
	}

	public Boolean getPrimeiroLogin() {
		return this.primeiroLogin;
	}

	public void setPrimeiroLogin(Boolean primeiroLogin) {
		this.primeiroLogin = primeiroLogin;
	}

	public String getTipoUsuario() {
		return this.tipoUsuario;
	}

	public void setTipoUsuario(String tipoUsuario) {
		this.tipoUsuario = tipoUsuario;
	}

	public String getNome() {
		return this.nome;
	}

	public void setNome(String nome) {
		this.nome = nome;
	}

	public String getEmail() {
		return this.email;
	}

	public void setEmail(String email) {
		this.email = email;
	}
	
	public Date getDataRegistro() {
		return this.dataRegistro;
	}

	public void setDataRegistro(Date dataRegistro) {
		this.dataRegistro = dataRegistro;
	}

	public Character getStatusRegistro() {
		return this.statusRegistro;
	}

	public void setStatusRegistro(Character statusRegistro) {
		this.statusRegistro = statusRegistro;
	}
	
	public Set<Atleta> getAtletas() {
		return atletas;
	}

	public void setAtletas(Set<Atleta> atletas) {
		this.atletas = atletas;
	}

	@Override
	public Long getIdentificacao() {
		return id;
	}

	@Override
	public int hashCode() {
		final int prime = 31;
		int result = 1;
		result = prime * result + ((id == null) ? 0 : id.hashCode());
		return result;
	}

	@Override
	public boolean equals(Object obj) {
		if (this == obj)
			return true;
		if (obj == null)
			return false;
		if (getClass() != obj.getClass())
			return false;
		Usuario other = (Usuario) obj;
		if (id == null) {
			if (other.id != null)
				return false;
		} else if (!id.equals(other.id))
			return false;
		return true;
	}
	
}
